export const arcadeGames: string[] = [
  "720°","After Burner","Aliens: Extermination","Anteater","Area 51","Arkanoid","Asteroids","Asteroids Deluxe",
  "Astro Fighter","Atari Football","Baby Pac-Man","Batman","Battlezone","Berzerk","Black Widow","Blasteroids",
  "BurgerTime","Carnival","Centipede","Crazy Climber","Crazy Taxi","Crossbow","Crystal Castles",
  "Dance Dance Revolution Extreme","Darkstalkers: The Night Warriors","Defender","Dig Dug","Donkey Kong",
  "Donkey Kong Jr.","Dragon's Lair","Dragon's Lair II: Time Warp","Escape from the Planet of Robot Monsters",
  "Family Guy Bowling","The Fast and the Furious","Frogger","Galaga","Galaxian","Gauntlet II",
  "Ghost Squad: Evolution","Ghouls'N Ghosts","Golden Axe","Gorf","Gravitar","Guitar Hero Arcade","Gyruss",
  "Hydro Thunder (x4)","Ice Cold Beer","Indiana Jones and the Temple of Doom","Initial D (Arcade Stage v3)",
  "Ivan 'Ironman' Stewart's Super Off Road","Joust","Jungle King","Kangaroo","Kick Man","Killer Queen",
  "Lunar Lander","Lunar Rescue","Mad Planets","Marble Madness","Mario Bros.","Michael Jackson's Moonwalker",
  "Millipede","Missile Command","Monkey Ball","Moon Patrol","Mortal Kombat 4","Mr. Do!","Ms. Pac-Man",
  "NBA Jam: Tournament Edition","Net City Candy Cab","Omega Race","OutRun (Enhanced Edition)","OutRun 2",
  "Pac-Man","Pac-Man Battle Royale","Pac-Man Plus","Paperboy","Peter Pack Rat","Phoenix","Pleiades","Popeye",
  "Punch-Out!!","Q*bert","Qix","Return of the Jedi","RoadBlasters","Road Runner","Robotron 2084","R-Type",
  "Satan's Hollow","Scramble","Sharp Shooter","Silent Scope","The Simpsons","Sinistar","Smash TV","Solar Fox",
  "Space Ace","Space Duel","Space Fury","Space Harrier","Space Invaders Deluxe","Spy Hunter","Star Castle",
  "Stargate","Star Trek: Strategic Operations Simulator","Star Wars","Star Wars Battle Pod",
  "Star Wars Trilogy Arcade","Street Fighter II: Champion Edition","Super Chexx","Tank","Tapper",
  "Target: Terror","Tempest","Teenage Mutant Ninja Turtles","Terminator 2: Judgement Day","TETЯIS",
  "ThunderJaws","Time Pilot","Top Skater","Track & Field","Tron","Turbo OutRun (Deluxe)","Tutankham","Vanguard",
  "Venture","Vs. Duck Hunt","Wizard of Wor","X-Men: Children of the Atom","Zaxxon",
];

export const pinballMachines: string[] = [
  "AC/DC","The Addams Family","Airborne","Alice's Adventures in Wonderland","Alien","Alien Poker","Apollo 13",
  "Atlantis","Attack from Mars","The Avengers Infinity Quest","Barracora","Batman '66","Baywatch",
  "Black Knight Swords of Rage","Bowl-O","Buck Rogers","Cactus Canyon","Cirqus Voltaire","Cosmic Gunfight",
  "Creature from The Black Lagoon","Deadpool","Dr. Dude and his Excellent Ray","Dracula",
  "Dungeons & Dragons: The Tyrant's Eye","Eight Ball Deluxe","Elvira and the Party Monsters",
  "Elvira House Of Horrors","F-14 Tomcat","Fathom (Mermaid Edition)","Firepower","Fish Tales","Flash Gordon",
  "Foo Fighters","Four Million B.C.","FunHouse","Galaxy","The Getaway: High Speed II","Ghost Busters",
  "Godzilla (Stern)","Gorgar","Guardians of the Galaxy","Guns N' Roses","Guns N' Roses: Not In This Lifetime",
  "Halloween — Collector's Edition","Harlem Globetrotters On Tour","Haunted House","Heavy Metal","High Speed",
  "The Hobbit","Indiana Jones the Pinball Adventure","Indianapolis 500","Iron Maiden: Legacy of the Beast",
  "Iron Man","Jack·Bot","James Bond 007","Jaws","Jurassic Park (Stern)","King Kong: Myth of Terror Island",
  "Labyrinth","The Lord of the Rings","Medieval Madness","Metallica","Monster Bash","The Munsters",
  "Nitro Ground Shaker","Old Chicago","The Party Zone","Pinball Magic","Pirates of the Caribbean",
  "Pulp Fiction (Bad Mother Flipper LE)","Revenge from Mars","Riverboat Gambler","Road Kings","Robocop",
  "Scared Stiff","The Shadow","Sorcerer","Space Shuttle","Space Station","Spooksville","Stargate","Stars",
  "Star Trek","Star Trek: The Next Generation","Star Wars (Stern)","Star Wars Episode 1",
  "Star Wars: Fall of the Empire","Stranger Things","Surfer","Swords of Fury","Tales of the Arabian Nights",
  "Taxi","Teenage Mutant Ninja Turtles","Terminator 2: Judgment Day","Theatre of Magic","Time Warp",
  "Tron Legacy","Twilight Zone","The Uncanny X-Men","The Walking Dead","Whirlwind","White Water",
  "The Who's Tommy Pinball Wizard","Wizard!","World Poker Tour","The X-Files","Xenon",
];

export const tournamentSchedule: { date: string; note: string }[] = [
  { date: "May 9, 2026", note: "Adults & Kids — Kids 10:45 AM / Adults 1:00 PM" },
  { date: "June 13, 2026", note: "Adults & Kids — Kids 10:45 AM / Adults 1:00 PM" },
  { date: "July 11, 2026", note: "Adults & Kids — Kids 10:45 AM / Adults 1:00 PM" },
  { date: "August 8, 2026", note: "Adults & Kids — Kids 10:45 AM / Adults 1:00 PM" },
  { date: "September 12, 2026", note: "Adults & Kids — Kids 10:45 AM / Adults 1:00 PM" },
  { date: "October 10, 2026", note: "Adults & Kids — Kids 10:45 AM / Adults 1:00 PM" },
  { date: "November 14, 2026", note: "Adults & Kids — Kids 10:45 AM / Adults 1:00 PM" },
  { date: "December 12, 2026", note: "Tracy's Pintastic — Adults Only (details TBA)" },
  { date: "January 2027", note: "Starfighters Pinball Festival (SPF) — details to come" },
  { date: "February 13, 2027", note: "Adults & Kids — Kids 10:45 AM / Adults 1:00 PM" },
  { date: "March 13, 2027", note: "Adults & Kids — Kids 10:45 AM / Adults 1:00 PM" },
  { date: "April 10, 2027", note: "Adults & Kids — Kids 10:45 AM / Adults 1:00 PM" },
];
